services:

  auth-service:
    build:
      context: ./services/auth-service
    container_name: attendance-auth
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/attendance_auth
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongodb

  student-service:
    build:
      context: ./services/student-service
    container_name: attendance-student
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      MONGO_URI: mongodb://mongodb:27017/attendance_student
    depends_on:
      - mongodb

  attendance-service:
    build:
      context: ./services/attendance-service
    container_name: attendance-service
    ports:
      - "5002:5002"
    environment:
      PORT: 5002
      MONGO_URI: mongodb://mongodb:27017/attendance_attendance
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongodb

  gateway:
    build:
      context: ./services/gateway
    container_name: attendance-gateway
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - auth-service
      - student-service
      - attendance-service

  mongodb:
    image: mongo:7
    container_name: attendance-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: